- name: Golang
  logo: go
  url: https://golang.org/
  color: '#7FD6EA'
  projects:
    - url: https://github.com/Matt-Gleich/fgh
    - url: https://github.com/Matt-Gleich/gh_fsync
    - url: https://github.com/Matt-Gleich/nuke
    - url: https://github.com/Matt-Gleich/logoru
    - url: https://github.com/Matt-Gleich/statuser

- name: Python
  logo: python
  url: https://www.python.org/
  color: '#3C78A9'
  projects:
    - url: https://github.com/Matt-Gleich/profile_stack
    - url: https://github.com/Matt-Gleich/Contribution-Hat
